# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
variables:
- name  : 'test'
  value : 'tests/ci/run_pytest.py'
- name  : 'testfolder'
  value : './tests/unit'
- name  : 'testmarkers'
  value : '"not notebooks and not spark and not gpu"'
- name  : 'junitxml'
  value : 'reports/test-unit.xml'
- name  : 'maxnodes'
  value : 4
- name  : 'reponame'
  value : 'Recommenders'
- name  : 'branch'
  value : 'TestJobs'
- name  : 'clustername'
  value : 'reco-cpu-test2'
- name  : 'vmsize'
  value : 'STANDARD_D3_V2'
- name  : 'dockerproc'
  value : 'cpu'
- name  : 'expname'
  value : 'cpu_unit_tests'  
- name : subscription_id
  value: 0ca618d2-22a8-413a-96d0-0f1b531129c3

trigger: none

pr:
- staging 
- master
  
pool:
 vmImage: 'ubuntu-16.04'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'
  displayName: 'Use Python 3.6'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734(0ca618d2-22a8-413a-96d0-0f1b531129c3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
        python scripts/generate_conda_file.py --name reco 
  displayName: 'generate_conda_file.py'

- template: ../tests/ci/env-setup.yml 

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734(0ca618d2-22a8-413a-96d0-0f1b531129c3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
     python scripts/generate_conda_file.py --name reco 
  displayName: ' generate_conda_file.py'

- task: AzureCLI@2
  inputs:
    azureSubscription: 'AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734(0ca618d2-22a8-413a-96d0-0f1b531129c3)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      python tests/ci/submit_azureml_pytest.py --subid $(subscription_id) --testfolder $(testfolder) --testmarkers $(testmarkers) --clustername $(clustername) --expname $(expname) --dockerproc $(dockerproc) --junitxml $(junitxml) --reponame $(reponame) --branch $(branch)
  displayName: 'submit_azureml_pytest'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/test-*.xml'
  inputs:
    testResultsFiles: '**/test-*.xml'
    failTaskOnFailedTests: true
  condition: succeededOrFailed()
