# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
#
variables:
  testmarkers: "not notebooks and not spark and not gpu"
  clustername: 'reco-cpu-test2'
  expname: 'cpu_unit_tests'
  subscription_id: '0ca618d2-22a8-413a-96d0-0f1b531129c3'
  subscription_name: 'AG-AzureCAT-AIDevOps-Test-COGSNonProd-IO1685734(0ca618d2-22a8-413a-96d0-0f1b531129c3)'
  AgentName: 'ubuntu-16.04'

trigger:
- master

jobs:
- job: notebook_cpu_tests
  displayName : 'CPU Unit Tests'
  pool:
    name: $(AgentName)

  steps:
  - template: steps/cpu_test_steps.yml
    parameters:
      testmarkers: $(testmarkers)
      clustername: $(clustername)
      expname: $(expname)
      conda: $(cpu_conda)
      subscription_id: $(subscription_id)
      subscription_name: $(subscription_name)